# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'websocket-chatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for websocket-chatApp
  pod 'Starscream'
  pod 'SnapKit'

end
